### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by rm-rf-etc** [mattmazzola/dotstar#2]
Please add more content to the readme. Took me a while to figure out that the set() method doesn't push an update to the LED's. I think the chances are good that many people who want to use this won't have experience in JS and won't be able to recognize typescript, so I think it's reasonable to provide this library in standard JS to make it more approachable.

**Comment by mattmazzola** [comment]
> Please add more content to the readme.

This is too vague to take action.  The README.md already walks through setup and every method the library exposes, I don't understand what more you want other than a fully working application.  In that case it would be as separate repo. This library even comes with tests which show usage.

> Took me a while to figure out that the set() method doesn't push an update to the LED's.

Every example in the README that changes the led strip uses `sync()`.
There are even comments in the tests which say things like: 
**all() does not update the LED strip only sets the memory for the next sync**
https://github.com/mattmazzola/dotstar/blob/master/test/dotstar.spec.ts#L26

Also, if set directly wrote to the LED strip the performance would be terrible.  There has to be a way to manipulate a local buffer without paying cost of writing to the SPI bus for every change.  If you want to write a wrapper around dotstart that writes on every change you can do this very easily but this isn't a concern for this library as it adds redundant API surface area and thus confusion.

> I think the chances are good that many people who want to use this won't have experience in JS and won't be able to recognize typescript, so I think it's reasonable to provide this library in standard JS to make it more approachable.

This is an opinion and I disagree. TypeScript is compiled to JavaScript so it's already provided in 'standard' JS. TypeScript is also self documenting and eases barrier to entry as new-comers who don't know the library can easily explore the methods without reading the source code.  Standard JS does not provide this and it would be downgrade to change it to that.  You are welcome to fork this into your own library.
